// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ierqtqgjmkvusdwvhfxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllcnF0cWdqbWt2dXNkd3ZoZnh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NDEwNzksImV4cCI6MjA3MjAxNzA3OX0.UCXD9eqvudCTGBBUgUtrDfTHAsRbfm4n_m-0Y1Ae6hY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});